{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-helm3-release.serviceAccountName" . }}
  labels:
{{ include "demo-helm3-release.labels" . | nindent 4 }}
{{- end -}}
